/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Alexander Antipov (https://sketchfab.com/Dessen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-teeth-c4c569f0e08948e2a572007a7a5726f2
Title: Human teeth
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Gums_GumsMaterial_0.geometry}
        material={materials.GumsMaterial}
      />
      <mesh
        geometry={nodes.Teeth_TeethMaterial_0.geometry}
        material={materials.TeethMaterial}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
