/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: dewa (https://sketchfab.com/dewa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/teeth-3a0fb31b9d864b27a0846aca8579461c
Title: Teeth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4.135}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.Gums} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Gums} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Gums} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Teeth} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Teeth} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Tongue} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
